---
title: "Think Stats - R code"
author: "Gabriel Florit"
output:
  html_document:
    self_contained: true
---

```{r, results='hide', warning=F, message=F}
library(dplyr)
library(ggplot2)
library(effsize)
library(StataDCTutils)
```

```{r, echo=F}
setwd("~/Documents/other/thinkstats2-r-code")
# parse STATA dictionary file
#fempregdict <- dct.parser('./2002FemPreg.dct')

# convert dictionary to csvkit schema
#csvkit.schema(fempregdict)

# convert data file to csv
#csvkit.fwf2csv(datafile='2002FemPreg.dat', schema='2002FemPreg.dct.csv', output='2002FemPreg.csv')

```

## 1.6 Transformation
```{r, warning=F}

fempreg <- read.csv('data/2002FemPreg.csv', row.names=NULL) %>%
	mutate(
		agepreg = agepreg / 100,
		birthwgt_lb = ifelse(birthwgt_lb > 20, NA, birthwgt_lb),
		birthwgt_oz = plyr::mapvalues(birthwgt_oz, c(97, 98, 99), c(NA, NA, NA)),
		totalwgt_lb = birthwgt_lb + birthwgt_oz / 16,
		firstbaby = ifelse(birthord == 1, 'first', 'other')
	)

```

## 2.3 Plotting histograms
```{r, warning=F}

live <- fempreg %>%
	filter(outcome == 1)

# histogram of pound part of birth weight
ggplot(live, aes(birthwgt_lb)) + geom_histogram(binwidth=1)

# histogram of ounce part of birth weight
ggplot(live, aes(birthwgt_oz)) + geom_histogram(binwidth=1)

# histogram of mother's age at end of pregnancy
ggplot(live, aes(agepreg)) + geom_histogram(binwidth=1)

# histogram of pregnancy length in weeeks
ggplot(live, aes(prglngth)) + geom_histogram(binwidth=1)

```

## 2.5 Outliers
```{r, warning=F}

# Get 10 lowest values
plyr::count(live$prglngth) %>% head(10)

# Get 10 highest values
plyr::count(live$prglngth) %>% tail(10)

```

## 2.6 First babies
```{r, warning=F}

live %>%
	ggplot(aes(x=prglngth, fill=firstbaby)) +
	geom_histogram(binwidth=1, position='dodge') +
	xlab('weeks') +
	xlim(27, 46)
	
```

## 2.8 Variance
```{r, warning=F}

mean(live$prglngth)
var(live$prglngth)
sd(live$prglngth)

```

## 2.9 Effect size
```{r, warning=F}

# Calculate Cohen's d for pregnancy length of first babies vs others

cohen.d(
	(live %>% filter(birthord == 1))$prglngth,
	(live %>% filter(birthord > 1))$prglngth
)

```

## 3.2 Plotting PMFs
```{r, warning=F}

firstbabyfreqs <- live %>%
	group_by(prglngth, firstbaby) %>%
	summarise(count = n(), freq = nrow(.[.$firstbaby == firstbaby, ])) %>%
	mutate(freq = count/freq)

p <- firstbabyfreqs %>%
	ggplot(aes(x=prglngth, y=freq, fill=firstbaby, color=firstbaby)) +
	xlim(27, 46) +
	xlab('weeks') + ylab('probability')

p1 <- p + geom_bar(stat='identity', position='dodge')
p2 <- p + geom_step(stat='identity')

Rmisc::multiplot(p1, p2, cols=2)
	
```

## 3.3 Other visualizations
```{r, warning=F}

firstbabyfreqs %>%
	group_by(prglngth) %>%
	arrange(firstbaby) %>%
	summarize(difference = 100*(first(freq) - last(freq))) %>%
	ggplot(aes(x=prglngth, y=difference)) +
	geom_bar(stat='identity') +
	xlim(34, 46) +
	xlab('weeks') + ylab('percentage points')

```
































